name: Deploy Frontend

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3

      - name: SSH to Ansible server and run playbook
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 34.207.234.147     # Ansible Server Public IP
          username: ubuntu
          key: ${{ secrets.ANSIBLE_SSH_KEY }}
          script: |
            cd /etc/ansible
            ansible-playbook frontend.yml
