name: Deploy Frontend

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Ansible Frontend Deployment
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: 34.207.234.147
          username: ubuntu
          key: ${{ secrets.-----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
QyNTUxOQAAACCXSCgkh2eLxmUeJ/1WTFzlR4t/qoFw35L43POYp4HF6QAAAJAmmEyOJphM
jgAAAAtzc2gtZWQyNTUxOQAAACCXSCgkh2eLxmUeJ/1WTFzlR4t/qoFw35L43POYp4HF6Q
AAAEBPqvqKcLXG7Wr1tQ3yb9Ba22V74gAnz7inFTq6tfdfnZdIKCSHZ4vGZR4n/VZMXOVH
i3+qgXDfkvjc85ingcXpAAAAC2Fuc2libGUta2V5AQI=
-----END OPENSSH PRIVATE KEY-----}}
          script: |
            ansible-playbook frontend.yml
