name: Deploy Frontend

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Run Ansible Frontend Deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: <ansible-ip>
          username: ubuntu
          key: ${{ secrets.ANSIBLE_SSH_KEY }}
          script: |
            ansible-playbook frontend.yml
